trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration=production --base-href=/reaction-sport/
  displayName: 'npm install and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'github.com_pillihuaman'  # Aquí va la Service Connection
    appName: 'alamodaperu'  # Nombre de la aplicación en Azure
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'zipDeploy'